services:
    ipmiview:
        container_name: xtekipmiview
        image: xtekllc/xtekipmiview:latest
        ports:
          - 8181:8080
          - 5959:5900
        volumes:
          - ./config:/opt/IPMIView
